# Site
name: "Trafiklab"
title: "Trafiklab"
description: "Together we make public transportation smarter"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: ''
disqus: ''
mailchimp-list: 'cf309d5e71'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  bert:
    name: Bert
    display_name: Bert
    avatar: 'assets/images/avatar.png'
    gravatar: ee27e112c3ea88e232c405764afec43f
    email: bert@trafiklab.se
    web: https://blog.trafiklab.se
    twitter: https://twitter.com/bertmarcelis
    description: "Systems engineer and open data expert at Samtrafiken, creating better public transport through open-source and open data."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
