# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/images'
collections:
  - name: 'Posts'
    label: 'Posts'
    extension: 'md'
    folder: '_posts/'
    fields:
      - { label: "Title", name: 'title', widget: "string" }
      - { label: "Layout", name: 'layout',  widget: "string" }
      - { label: "Author",  name: 'author', widget: "string" }
      - { label: "Categories",  name: 'categories', widget: "list" }
      - { label: "Image",  name: 'image', widget: "image" }
      - { label: 'Blog post content', name: 'body', widget: 'markdown'}
